# Generated by Django 4.0 on 2022-01-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('Credit_card_Type', models.CharField(max_length=30)),
                ('Credit_card_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Supplier', models.CharField(max_length=200)),
                ('Item_Size', models.IntegerField()),
                ('Dimension', models.IntegerField()),
                ('NeededFiles', models.URLField(verbose_name='Click here for medical record')),
                ('ProductPictures', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Company_Address', models.CharField(max_length=150)),
                ('Phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('Detail_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Specific_Details', models.TextField(max_length=200)),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.product')),
            ],
        ),
    ]
