# Generated by Django 4.0 on 2022-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Item_Size',
            new_name='Item_Size_pounds',
        ),
        migrations.AlterField(
            model_name='product',
            name='Dimension',
            field=models.CharField(max_length=200),
        ),
    ]
