# Generated by Django 4.0 on 2022-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_rename_item_size_product_item_size_pounds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='NeededFiles',
            field=models.URLField(verbose_name='Click here for product link'),
        ),
    ]
