# Generated by Django 4.0 on 2022-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_alter_product_neededfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Credit_card_Number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
