# Generated by Django 4.0 on 2022-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_alter_customer_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bought_item',
            field=models.ManyToManyField(to='storeapp.Product'),
        ),
    ]
