# Generated by Django 4.0 on 2022-01-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_customer_bought_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bought_item',
        ),
        migrations.AddField(
            model_name='customer',
            name='bought_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storeapp.product'),
            preserve_default=False,
        ),
    ]
