# Generated by Django 4.0 on 2022-02-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_remove_customer_bought_item_customer_bought_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='Supplier_company',
            field=models.ForeignKey(default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='storeapp.supplier'),
        ),
    ]
