# Generated by Django 4.0 on 2022-02-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_alter_product_supplier_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Supplier_company',
        ),
    ]
