# Generated by Django 4.0 on 2022-02-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0011_alter_product_supplier_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Supplier_company',
            new_name='Supplier',
        ),
    ]
