# Generated by Django 4.0 on 2022-02-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_rename_supplier_company_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delievry_date', models.DateField()),
                ('Price', models.CharField(max_length=100)),
                ('Credit_card_Number', models.CharField(max_length=100)),
                ('Customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.customer')),
                ('bought_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.product')),
            ],
        ),
    ]
