# Generated by Django 4.0 on 2022-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bought_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Dimension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Item_Size_pounds',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Supplier',
        ),
        migrations.AddField(
            model_name='customer',
            name='Diagnosis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
